Fixed UserErrors, imports, and Documentation
Added a tester to check that the parser works correctly. Fixed imports
not workin due to path, UserErrors not being raised due to inheritance,
and added a tester.

  .gitignore; Added __pycache__ ignore rule.
+ tester.py: Added a new tester file to test the parser.
argpars/:
    __init__: Changed export pathing to use relative path.
    ArgOption: Changed imports to relative.
    ArgParser: Changed imports to relative. Added more specific errors
for number of option arguments.
    UserError: Changed imports to relative. Added a method for
generating an error about too no arguments when they are required.